name: Build & Deploy Vite Project to GitHub Pages

# Run on a 'push' to the main branch
on:
  push:
    branches:
      - main

# Run these jobs with 'write' permissions
permissions:
  contents: write

jobs:
  # The build job
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Upload the artifact
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  # The deploy job
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download the artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true

  # Update the timestamp
  update_timestamp:
    name: Update last_built.txt
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create Timestamp File
        run: |
          echo "Last built: $(TZ='America/Chicago' date +'%D, %T')" > last_built.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_built.txt
          git commit -m "Update last build timestamp"
          git push
